apiVersion: batch/v1
kind: Job
metadata:
  name: trombones-job
spec:
  template:
    spec:
      containers:
      - name: trombones-job
        image: yash5090/trombones:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
