apiVersion: v1
kind: Service
metadata:
  name: trombones-service
  namespace: web-app
spec:
  selector:
    app: trombones
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
